### ISSUE TITLE
Add about us screen to the app

### ISSUE THREAD

**Issue by Lancear** [DIT113-V22/group-01#12]
As a user, I want to know what the app is all about so that I can learn more about the cool devs.

<br>

**Acceptance Criteria:**
- [x] An about screen is added to the app with a description of why we created it
- [x] Contact details and GitHub link are added to this page for support (u wish lmao)
- [x] This page can be found within at most 3 clicks in the app

**Comment by GeorgZs** [comment]
Captured on Pixel 3 XL
![image](https://user-images.githubusercontent.com/62954053/164023433-93334b82-fbc0-4b76-abd8-43d4cfbff325.png)
