### ISSUE TITLE
Add simple car controls and display data

### ISSUE THREAD

**Issue by Lancear** [DIT113-V22/group-01#14]
As a user, I want to be able to see all controls of the car and computed car data represented in the app so that I can drive the car and react to situations based on data.

<br>

**Acceptance Criteria:**
- [x] The sensors are active during driving
- [x] All commands are transmitted via the java sdk
- [x] Necessary UI for control of the car is there
  - [x] The car changes speed when the user accelerates or brakes.
  - [x] The car changes directions when the user steers.
- [x] The implementation is tested manually
- [x] The implementation is tested manually for drunk drivers 🍻

**Comment by plepisnew** [comment]
Requesting testers for last criteria (jk i tested it)

**Comment by plepisnew** [comment]
[1d77109 comment 71945577](https://github.com/DIT113-V22/group-01/commit/1d7710987196351db00423ca76792e6820fce3bf#commitcomment-71945577) describes problems for this issue
