### ISSUE TITLE
Define the Quiz Data Model

### ISSUE THREAD

**Issue by GeorgZs** [DIT113-V22/group-01#33]
As an efficient developer team, we want to know how the quiz data will look, in order to work simultaneously on our tasks.
Acceptance Criteria

- [x] A Question class is created (take milestone 5 into consideration)
  - [x] Contains the question, explanation, answers, correct answer index, and categories.
- [x] A UserAnswer class is created
  - [x] Contains the given answer index, a correct/wrong flag
- [x] A Category class is created
  - [x] Contains the category name and a flag if it is a special category
  - [x] Review, exam, and all are special categories
- [x] A QuizState class is created (define method stubs for changing state as well)
  - [x] Contains a flag whether the user is currently taking a quiz
  - [x] Contains the questions (simply hardcoded for now), user answers, score
  - [x] Contains helper methods for the ui (nr of questions, current question nr, etc.)
- [x] All developers agree on the data model and a wiki page is created
  - [x] The MqttCar class is added (static and @Override attributes can be ignored)
  - [x] The CarState class is added (private and static attributes can be ignored)
  - [x] The Question class is added (private and static attributes can be ignored)
  - [x] The UserAnswer class is added (private and static attributes can be ignored)
  - [x] The QuizState class is added (private and static attributes can be ignored)

**Comment by JohnWebb00** [comment]
Removed part of the acceptance criteria as it was deemed not relevant.

- [x] A UserAnswer class is created
  - [x] Contains the given answer index, a correct/wrong flag ~~,and a datetime~~

**Comment by JohnWebb00** [comment]
- [x] A Question class is created (take milestone 5 into consideration)
  - [x] Contains the question, explanations, answers, correct answer index, and categories, ~~all previous user answers to this question~~
