### ISSUE TITLE
Add review category management

### ISSUE THREAD

**Issue by GeorgZs** [DIT113-V22/group-01#40]
As a user, I want to have a review category with the questions I answered incorrectly, in order to easily practise the questions I struggle with.

**Acceptance Criteria:**
- [x] Questions answered correctly the last 2 times they were asked are removed from the review category (use user answers at the question to check this)
- [x] When the user answers a question incorrectly it is flagged for review by changing the needsReview index to 1.
  - [x] Wrong user answers with no answer index set are ignored (user out of time)
- [x] The implementation of Review categories is manually tested. (potentially unit tests)

**Comment by Lancear** [comment]
>  Questions answered correctly the last 2 times they were asked are removed from the review category (use user answers at the question to check this)

Changed to last time since we cannot easily store the log with all user answers for a question in SQLite without creating multiple tables and associations
