### ISSUE TITLE
Set the cars spawn position in the emulator

### ISSUE THREAD

**Issue by GeorgZs** [DIT113-V22/group-01#46]
As a user, I want to be able to spawn my car at different locations in the emulator, so that I can start driving at different locations 

**Acceptance Criteria:**
- [ ] Research is done whether it is remotely easy to change the cars’ position with an emulator extension
- [ ] If setting the cars’ position is feasible, allow the app to communicate to the emulator, maybe via a mqtt topic?
- [ ] When opening the practice mode show a popup with predefined spawn locations
  - [ ] When choosing one of them close the popup and set the cars position
- [ ] Add a way to open the spawn point popup manually for if the user changes their mind

**Comment by Lancear** [comment]
Will be moved to Milestone 9

**Comment by GeorgZs** [comment]
_Shows that upon loading in the car it checks for the set spawn location, therefore I dont think there is a way to dynamically change the spawn location of the car._
<br>
![image](https://user-images.githubusercontent.com/62954053/167949662-1ad30b52-28a5-460f-94da-ed3b995b4962.png)

**Comment by GeorgZs** [comment]
![image](https://user-images.githubusercontent.com/62954053/167955575-cf948e9d-d56e-4ec3-9dee-ca5788a8c6f8.png)
<br>
Some progress!! 💯

**Comment by plepisnew** [comment]
Moving to Milestone 10
