### ISSUE TITLE
Add blinkers to the car

### ISSUE THREAD

**Issue by Lancear** [DIT113-V22/group-01#5]
As a user, I should be able to use a blinker to indicate the direction that I'm turning so that I can make it a habit so that I can pass my driving test.

<br>

**Acceptance Criteria:**
- [x] Toggle the blinkers off when the angle of turning is in the opposite direction
- [x] The car listens to blinking commands via a MQTT topic (left / right / off)
- [x] The implementation is tested
- [x] This functionality is added to the java sdk
- [x] This integration in the java sdk is tested

**Comment by plepisnew** [comment]
Task 1-3 fixed with commit d581d9db9937d39059cde823fbbbbf1c4eff44bc AND 7b6e553096a140ff204c63abd3950016bcc22bf3
