### ISSUE TITLE
Create city environment

### ISSUE THREAD

**Issue by JohnWebb00** [DIT113-V22/group-01#70]
As a user, I want to practice driving in an urban setting so that the environment is more representative of where I may be driving.

Acceptance Criteria
- [x] A design is drawn up beforehand
- [x] An SMCE mod of the map is created.
- [x] The car is loadable in the map.
- [x] The car is fully operational in the map
- [x] Sensor Data can be transmitted via MQTT
- [x] Control actions can be received via MQTT
- [x] The map has hidden borders
- [x] Car cannot fall off the map
- [x] Cannot see the edge of the map
- [x] Map contains the expected models and structures for simulating a city-like environment
- [x] Map has grid-like road structure, junctions, and at least one one-way street
- [x] Map contains buildings lining the roads such as apartment buildings, small businesses, and skyscrapers.

**Comment by plepisnew** [comment]
c202aae5be285d17969ac8d6c3435e9ab69a8880 refers to this issue

**Comment by plepisnew** [comment]
![download](https://user-images.githubusercontent.com/90762420/169603308-c1c4ca77-2f43-4dba-a0a8-b4d9be09e3c0.png)
Explorable area vast enough to let users see the environment and tiny enough to hide map borders from players

**Comment by plepisnew** [comment]
Street Signs are moved to Milestone 10
