### ISSUE TITLE
Update the wiki

### ISSUE THREAD

**Issue by JohnWebb00** [DIT113-V22/group-01#72]
As a TA, I want to see more documentation, so that I have a better idea of the group's progress and roadmap.

Acceptance Criteria
- [x] Add more detailed descriptions to the milestones (also in the wiki and the list of milestones on the project idea wiki)
- [x] Add a class diagram for the app
- [x] Add a EER diagram for the database
- [x] Create a user manual page with screenshots of the app

**Comment by GeorgZs** [comment]
Class Diagram and EER Diagram <br>
https://github.com/DIT113-V22/group-01/wiki/10.-UML-Diagrams

**Comment by GeorgZs** [comment]
User Manual <br>
https://github.com/DIT113-V22/group-01/wiki/9.-User-Manual

**Comment by GeorgZs** [comment]
Milestones updated in the wiki (all places)
<br>

Here is the first sign of it being updated: https://github.com/DIT113-V22/group-01/wiki/Milestone-1:-Control-Car-Via-Api

**Comment by GeorgZs** [comment]
Wiki is done!!
